# This script will generate all the non-standard pathways SVG specified in a pathways list file (generated by run_preprocess.sh)

OUTPUT=$2
PATHWAY_LIST=$1
echo "Using list of chebiId in $PATHWAY_LIST"
echo "Ouputing to $OUTPUT"

echo "Generating pathways SVG.\n"

mvn -e -X exec:java -Dexec.mainClass="uk.ac.ebi.pamela.layoutpipeline.exec.PAMELAMultiQueryPipelineExec" -Dexec.args="$OUTPUT $PATHWAY_LIST"
