# This script will generate all standard pathways SVG specified in a pathways list file (generated by run_preprocess.sh)

WORKING_FOLDER=$1

echo "Working folder $WORKING_FOLDER"

echo "Generating pathways SVG.\n"

mvn -e -X exec:java -Dexec.mainClass="uk.ac.ebi.pamela.layoutpipeline.exec.PAMELADirectMultiPathwayPipelineExec" -Dexec.args="$WORKING_FOLDER"
